# Generated by Django 4.2.3 on 2023-07-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ic', models.CharField(max_length=100)),
                ('disease', models.CharField(default='', max_length=200)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'bookingdetails',
            },
        ),
        migrations.CreateModel(
            name='BookingChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_9am', models.BooleanField(default=True)),
                ('slot_12pm', models.BooleanField(default=False)),
                ('slot_3pm', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bookingchecker',
            },
        ),
    ]
