# Generated by Django 4.2.3 on 2023-07-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingchecker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
