# Generated by Django 4.2.3 on 2023-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookingchecker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingchecker',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookingchecker',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
